# Generated by Django 3.1 on 2020-08-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(help_text="CSS FA icon class without 'fa-' prefix.", max_length=32, verbose_name='Icon'),
        ),
    ]
