# Generated by Django 3.1 on 2020-08-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200829_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this project.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='', help_text='Name of this project.', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this task.', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='', help_text='Name of this task.', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this badge.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this challenge.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, help_text='User description.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this submission.', verbose_name='Description'),
        ),
    ]
