# Generated by Django 3.1 on 2020-08-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200829_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='rewards',
            field=models.ManyToManyField(blank=True, help_text='Badges awareded to users that complete projects for this challenge.', related_name='challenges', to='app.Badge', verbose_name='Rewards'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this challenge.', related_name='challenges', to='app.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, help_text='Badges awarded to this user.', related_name='profiles', to='app.Badge', verbose_name='Badges'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this user.', related_name='profiles', to='app.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Those who have completed tasks for this project.', related_name='contributed_projects', to='app.Profile', verbose_name='Contributors'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this project.', related_name='projects', to='app.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags associated with this task.', related_name='tags', to='app.Tag', verbose_name='Tags'),
        ),
    ]
