# Generated by Django 3.1 on 2020-08-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end',
            field=models.DateTimeField(blank=True, help_text='End date and time when projects can no longer be created for this challenge.', verbose_name='Challenge End'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start',
            field=models.DateTimeField(blank=True, help_text='Start date and time when projects can be created for this challenge.', verbose_name='Challenge Start'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('S', 'Skill Level'), ('L', 'Location'), ('K', 'Knowledge'), ('I', 'Importance')], help_text='Category of this tag which determines where it is available and presented.', max_length=1, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('T', 'TODO'), ('I', 'In-Progress'), ('C', 'Completed')], help_text='Status of this task.', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Requested Changes'), ('R', 'Rejected'), ('A', 'Accepted')], help_text='Status of this submission.', max_length=1, verbose_name='Status'),
        ),
    ]
