# Generated by Django 3.1 on 2020-09-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200902_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, help_text='Those who have contributed to this project.', related_name='contributed_projects', to='app.Profile', verbose_name='Contributors'),
        ),
    ]
