# Generated by Django 3.1 on 2020-09-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200902_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='creators',
            field=models.ManyToManyField(help_text='Creators of this challenge which can edit its properties.', related_name='created_challenges', to='app.Profile', verbose_name='Creators'),
        ),
    ]
