# Generated by Django 3.0.10 on 2020-09-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200918_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
