# Generated by Django 3.1 on 2020-09-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200915_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end',
            field=models.DateTimeField(blank=True, help_text='End date and time when projects can no longer be created for this challenge.', null=True, verbose_name='Challenge End'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start',
            field=models.DateTimeField(blank=True, help_text='Start date and time when projects can be created for this challenge.', null=True, verbose_name='Challenge Start'),
        ),
    ]
