# Generated by Django 3.0.10 on 2020-09-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200918_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='creators',
            field=models.ManyToManyField(help_text='Creators of this challenge which can edit its properties. Removing yourself will make it impossible to edit this challenge.', related_name='created_challenges', to='app.Profile', verbose_name='Creators'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creators',
            field=models.ManyToManyField(help_text='Creators of this project which can edit its properties. Removing yourself will make it impossible for you to edit this project.', related_name='created_projects', to='app.Profile', verbose_name='Creators'),
        ),
    ]
