# Generated by Django 3.1 on 2020-09-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_tag_category'),
        ('app', '0013_auto_20200918_2317'),
    ]

    operations = [
    ]
