# Generated by Django 3.1 on 2020-11-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200919_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='one_liner',
            field=models.CharField(blank=True, help_text='A one line description of this challenge.', max_length=50, verbose_name='One Liner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='one_liner',
            field=models.CharField(blank=True, help_text='A one line description of this project.', max_length=50, verbose_name='One Liner'),
        ),
    ]
