# Generated by Django 3.1 on 2020-09-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200919_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, help_text='City of origin of user', max_length=30, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, help_text='Country of origin of user', max_length=30, null=True, verbose_name='country'),
        ),
    ]
