# Generated by Django 3.1 on 2020-11-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201127_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True, default='\n# Challenge Name\n\nA longer description of the project compared to the one liner.\n\n## Tasks\n\nProvide a simple, bulleted list of tasks that you would like project creators to accomplish:\n - Task 1\n - Task 2\n - Task 3\n\n## Extra Resources\n\nIf there are extra tools that you think project makers could benefit them, include them here.\n', help_text='Description of this challenge.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='\n# Project Name\n\nA longer description of the project compared to the one liner.\n\n## Features\n\nTalk about some cool things your project does here. You can use a:\n - Bulleted\n - List\n - Like\n - This\n\n## Installation\n\nYou should explain how to install the project in this section.\n 1. Numbered\n 2. Lists\n 3. Are\n 4. Useful\n', help_text='Description of this project.', verbose_name='Description'),
        ),
    ]
