# Generated by Django 3.1 on 2020-09-22 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20200919_1517'),
        ('app', '0013_auto_20200919_0144'),
    ]

    operations = [
    ]
