# Generated by Django 3.1 on 2021-01-11 22:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True, verbose_name='Location'),
        ),
    ]
