# Generated by Django 3.1 on 2020-10-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Latitude of this person, accurate to the city level.', max_digits=3, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Longitude of this person, accurate to the city level.', max_digits=4, null=True, verbose_name='Longitude'),
        ),
    ]
