# Generated by Django 3.1 on 2021-01-04 04:17

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SocialLinkAttachement = apps.get_model("app", "SocialLinkAttachement")

    # for each attachment, update the value of content with what was the .href property
    for attachement in SocialLinkAttachement.objects.using(db_alias).all():
        attachement.content = attachement.link.site % attachement.content
        attachement.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201127_0042'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.RemoveField(
            model_name='sociallinkattachement',
            name='link',
        ),
        migrations.AlterField(
            model_name='sociallinkattachement',
            name='content',
            field=models.CharField(help_text='The actual link.', max_length=2047, verbose_name='Link'),
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
