# Generated by Django 3.1 on 2021-02-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_profile_headline'),
        ('app', '0016_auto_20210103_2317'),
    ]

    operations = [
    ]
