# Generated by Django 3.1.7 on 2021-04-18 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20210217_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_image',
            field=models.ImageField(default='default_profile_bg.jpg', upload_to='profile_background_pics'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('upvoteCount', models.IntegerField()),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='comments',
            field=models.ManyToManyField(blank=True, to='app.Comment'),
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.ManyToManyField(blank=True, to='app.Comment'),
        ),
    ]
