# Generated by Django 3.1.7 on 2021-04-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210418_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='upvoteCount',
            field=models.IntegerField(default=0),
        ),
    ]
