# Generated by Django 3.1.7 on 2021-05-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210425_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True, default="\nA description of the challenge in layman's terms.\n\n##### Features to Implement\n- User interface (UI) to interact with ...\n- Algorithm that ...\n- Backend database to ...\n- Server to host the application for users to test out online \n\n##### Extra Resources and Guidelines\nIf there are extra tools that you think project makers could benefit from, include them here.\n", help_text='Description of this challenge.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, help_text='A headline for your profile', max_length=40, verbose_name='Headline'),
        ),
    ]
