# Generated by Django 3.1.7 on 2021-05-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210509_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default="\nA longer description of the project compared to the one liner.\n\n##### Features\n\nTalk about some cool things your project does here. You can use a:\n - Bulleted\n - List\n - Like\n - This\n\n##### How It's Built\nTalk about how you built this project in technical terms. Talk about the languages, frameworks, and tools you used\nto create this project. \n", help_text='Description of this project.', verbose_name='Description'),
        ),
    ]
